cmake_minimum_required(VERSION 3.18)

get_filename_component(KATAGO_ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
include("${KATAGO_ROOT}/cpp/cmake/C384ExactFfnDownAotPolicy.cmake")

function(set_down_manifest BATCH)
  if(BATCH EQUAL 28)
    set(_id
      "c384-s225-residual-ffn-down-m6300-k1024-n384-m128n128k32s3-natural-b28-abi1")
  elseif(BATCH EQUAL 24)
    set(_id
      "c384-s225-residual-ffn-down-m5400-k1024-n384-m128n128k32s3-natural-b24-abi1")
  else()
    message(FATAL_ERROR "unsupported fixture batch")
  endif()
  set(KATAGO_C384_FFN_DOWN_PACKAGE_SCHEMA 1 PARENT_SCOPE)
  set(KATAGO_C384_FFN_DOWN_PACKAGE_MODE PRODUCTION PARENT_SCOPE)
  set(KATAGO_C384_FFN_DOWN_SELECTED_BATCH ${BATCH} PARENT_SCOPE)
  set(KATAGO_C384_FFN_DOWN_SELECTED_ID "${_id}" PARENT_SCOPE)
  set(KATAGO_C384_FFN_DOWN_TACTIC_IDS "${_id}" PARENT_SCOPE)
  set(KATAGO_C384_FFN_DOWN_REGISTRY_PROVIDER registry.cu PARENT_SCOPE)
  set(KATAGO_C384_FFN_DOWN_GENERATED_INCLUDE_DIR include PARENT_SCOPE)
  set(KATAGO_C384_FFN_DOWN_GENERATED_HEADERS tactic.h PARENT_SCOPE)
  set(KATAGO_C384_FFN_DOWN_GENERATED_METADATA tactic.json PARENT_SCOPE)
  set(KATAGO_C384_FFN_DOWN_GENERATED_BRIDGES bridge.cu PARENT_SCOPE)
  set(KATAGO_C384_FFN_DOWN_GENERATED_OBJECTS tactic.o PARENT_SCOPE)
  set(KATAGO_C384_FFN_DOWN_GENERATED_FILE_SHA256 registry.cu 00 PARENT_SCOPE)
endfunction()

if(CASE STREQUAL "valid-down")
  set_down_manifest(28)
  set(KATAGO_C384_EXACT_FFN_DOWN_REQUESTED_ID "")
  katago_c384_ffn_down_resolve_manifest_policy()
  if(NOT KATAGO_C384_EXACT_EFFECTIVE_FFN_DOWN_TACTIC_ID STREQUAL
     KATAGO_C384_FFN_DOWN_SELECTED_ID)
    message(FATAL_ERROR "effective ID was not derived from the package")
  endif()
elseif(CASE STREQUAL "b24-down")
  set_down_manifest(24)
  katago_c384_ffn_down_resolve_manifest_policy()
elseif(CASE STREQUAL "shadowed-abi")
  file(MAKE_DIRECTORY
    "${CMAKE_CURRENT_LIST_DIR}/c384-b28-policy-shadow-fixture")
  file(WRITE
    "${CMAKE_CURRENT_LIST_DIR}/c384-b28-policy-shadow-fixture/c384_residual_aot_abi.h"
    "shadow")
  set_down_manifest(28)
  set(KATAGO_C384_FFN_DOWN_GENERATED_BRIDGES
    "${CMAKE_CURRENT_LIST_DIR}/c384-b28-policy-shadow-fixture/bridge.cu")
  katago_c384_ffn_down_resolve_manifest_policy()
elseif(CASE STREQUAL "incomplete-production")
  set(KATAGO_C384_EXACT_AOT_GENERATED_MANIFEST exact.cmake)
  set(KATAGO_C384_H12_FA4_PACKAGE_CMAKE fa4.cmake)
  set(KATAGO_C384_EXACT_AOT_PACKAGE_MODE PRODUCTION)
  set(KATAGO_C384_EXACT_AOT_SELECTED_BATCH 28)
  set(KATAGO_C384_H12_FA4_PACKAGE_MODE PRODUCTION)
  set(KATAGO_C384_H12_FA4_BATCHES 28)
  set(KATAGO_C384_EXACT_FFN_DOWN_PACKAGE_CMAKE "")
  katago_c384_validate_b28_production_bundle_policy()
elseif(CASE STREQUAL "complete-production")
  set(KATAGO_C384_EXACT_AOT_GENERATED_MANIFEST exact.cmake)
  set(KATAGO_C384_H12_FA4_PACKAGE_CMAKE fa4.cmake)
  set(KATAGO_C384_EXACT_FFN_DOWN_PACKAGE_CMAKE down.cmake)
  set(KATAGO_C384_EXACT_AOT_PACKAGE_MODE PRODUCTION)
  set(KATAGO_C384_EXACT_AOT_SELECTED_BATCH 28)
  set(KATAGO_C384_H12_FA4_PACKAGE_MODE PRODUCTION)
  set(KATAGO_C384_H12_FA4_BATCHES 28)
  set(KATAGO_C384_FFN_DOWN_PACKAGE_MODE PRODUCTION)
  set(KATAGO_C384_FFN_DOWN_SELECTED_BATCH 28)
  katago_c384_validate_b28_production_bundle_policy()
elseif(CASE STREQUAL "search-pair")
  set(KATAGO_C384_EXACT_AOT_GENERATED_MANIFEST exact-search.cmake)
  set(KATAGO_C384_H12_FA4_PACKAGE_CMAKE fa4-search.cmake)
  set(KATAGO_C384_EXACT_FFN_DOWN_PACKAGE_CMAKE "")
  set(KATAGO_C384_EXACT_AOT_PACKAGE_MODE SEARCH_PAIR)
  set(KATAGO_C384_H12_FA4_PACKAGE_MODE BATCH_SEARCH)
  katago_c384_validate_b28_production_bundle_policy()
else()
  message(FATAL_ERROR "unknown CASE=${CASE}")
endif()
