# Standalone, CPU-only checks. Also exercised directly by test_artifacts.py via cmake -P.
# Manifests protect bundle coherence, not the authenticity of an untrusted download.
function(_b11_fa4_expect json expected)
  string(JSON _value GET "${json}" ${ARGN})
  if(NOT "${_value}" STREQUAL "${expected}")
    message(FATAL_ERROR "Unexpected B11 FA4 field ${ARGN}: '${_value}', expected '${expected}'")
  endif()
endfunction()

function(_b11_fa4_hash path expected)
  if(NOT EXISTS "${path}" OR IS_DIRECTORY "${path}")
    message(FATAL_ERROR "Missing B11 FA4 artifact: ${path}")
  endif()
  string(LENGTH "${expected}" _length)
  if(NOT _length EQUAL 64 OR NOT "${expected}" MATCHES "^[0-9a-f]+$")
    message(FATAL_ERROR "Invalid B11 FA4 hash: ${path}")
  endif()
  file(SHA256 "${path}" _actual)
  if(NOT "${_actual}" STREQUAL "${expected}")
    message(FATAL_ERROR "B11 FA4 artifact hash mismatch: ${path}")
  endif()
endfunction()

function(_b11_fa4_validate_one dir prefix mode batch)
  set(_manifest_path "${dir}/${prefix}.json")
  if(NOT EXISTS "${_manifest_path}")
    message(FATAL_ERROR "Missing B11 FA4 manifest: ${_manifest_path}")
  endif()
  file(READ "${_manifest_path}" _json)
  if(batch EQUAL 0)
    _b11_fa4_expect("${_json}" 1 schema)
    _b11_fa4_expect("${_json}" 1 runtime_batch minimum)
    _b11_fa4_expect("${_json}" 96 runtime_batch maximum)
  else()
    _b11_fa4_expect("${_json}" 2 schema)
    _b11_fa4_expect("${_json}" "${batch}" fixed_batch)
    foreach(_bound IN ITEMS minimum maximum probe)
      _b11_fa4_expect("${_json}" "${batch}" runtime_batch ${_bound})
    endforeach()
    _b11_fa4_expect("${_json}" sm120 target)
    _b11_fa4_expect("${_json}" pointer_only tensor_abi)
    _b11_fa4_expect("${_json}" packed qkv_layout)
    _b11_fa4_expect("${_json}" 1152 qkv_stride)
    _b11_fa4_expect("${_json}" 384 output_stride)
  endif()
  _b11_fa4_expect("${_json}" "${prefix}" symbol_prefix)
  _b11_fa4_expect("${_json}" "${prefix}_prepare" prepare_symbol)
  _b11_fa4_expect("${_json}" "${prefix}_launch" launch_symbol)
  _b11_fa4_expect("${_json}" "${mode}" mode)
  _b11_fa4_expect("${_json}" 361 fixed_shape sequence)
  _b11_fa4_expect("${_json}" 12 fixed_shape heads)
  _b11_fa4_expect("${_json}" 32 fixed_shape head_dim)
  _b11_fa4_expect("${_json}" 128 tile m)
  _b11_fa4_expect("${_json}" 96 tile n)
  _b11_fa4_expect("${_json}" 1 tile stages)
  _b11_fa4_expect("${_json}" 128 tile threads)
  _b11_fa4_expect("${_json}" fp16 io)
  _b11_fa4_expect("${_json}" fp16 accumulation qk)
  _b11_fa4_expect("${_json}" fp16 accumulation pv)
  foreach(_suffix IN ITEMS .o .h _api.h _bridge.cpp)
    string(JSON _hash GET "${_json}" artifacts "${_suffix}" sha256)
    _b11_fa4_hash("${dir}/${prefix}${_suffix}" "${_hash}")
  endforeach()
  if(NOT batch EQUAL 0)
    # Do not accept a dynamic tensor header merely labelled as static.
    file(READ "${dir}/${prefix}.h" _header)
    set(_tensors mQ mK mV mO)
    if(mode STREQUAL "mask")
      list(APPEND _tensors mMask)
    endif()
    foreach(_tensor IN LISTS _tensors)
      if(NOT _header MATCHES "typedef[ \t\r\n]+struct[ \t\r\n]*\\{[ \t\r\n]*void[ \t\r\n]*\\*[ \t\r\n]*data[ \t\r\n]*;[ \t\r\n]*\\}[ \t\r\n]*${prefix}_Tensor_${_tensor}_t[ \t\r\n]*;")
        message(FATAL_ERROR "B11 FA4 static tensor ABI is not pointer-only: ${prefix}/${_tensor}")
      endif()
    endforeach()
    if(NOT _header MATCHES "float softmax_scale" OR NOT _header MATCHES "cudaStream_t stream")
      message(FATAL_ERROR "B11 FA4 static scale/stream ABI mismatch: ${prefix}")
    endif()
    file(READ "${dir}/${prefix}.o" _elf OFFSET 0 LIMIT 20 HEX)
    string(SUBSTRING "${_elf}" 0 12 _elf_magic)
    string(SUBSTRING "${_elf}" 36 4 _elf_machine)
    if(NOT _elf_magic STREQUAL "7f454c460201" OR NOT _elf_machine STREQUAL "3e00")
      message(FATAL_ERROR "B11 FA4 object is not little-endian ELF64 x86-64: ${prefix}")
    endif()
  endif()
endfunction()

# Fixed canonical paths are resolved from root; no executable path comes from JSON.
# Absolute provenance paths are informational so an intact bundle may be relocated.
function(b11_fa4_collect_artifacts root out_sources out_includes out_static)
  set(_sources)
  set(_includes)
  if(EXISTS "${root}/bundle.json")
    file(READ "${root}/bundle.json" _bundle)
    _b11_fa4_expect("${_bundle}" 2 schema)
    _b11_fa4_expect("${_bundle}" b11-fa4-static-packed format)
    string(JSON _count LENGTH "${_bundle}" entries)
    string(JSON _batches LENGTH "${_bundle}" batches)
    if(NOT _count EQUAL 4 OR NOT _batches EQUAL 2)
      message(FATAL_ERROR "B11 FA4 static bundle requires exactly four B13/B16 exact/mask entries")
    endif()
    _b11_fa4_expect("${_bundle}" 13 batches 0)
    _b11_fa4_expect("${_bundle}" 16 batches 1)
    set(_index 0)
    foreach(_batch IN ITEMS 13 16)
      foreach(_mode IN ITEMS exact mask)
        set(_prefix "b11_fa4_static_b${_batch}_${_mode}_m128_n96_s1")
        set(_relative "b${_batch}/${_mode}")
        set(_dir "${root}/${_relative}")
        _b11_fa4_expect("${_bundle}" "${_batch}" entries ${_index} batch)
        _b11_fa4_expect("${_bundle}" "${_mode}" entries ${_index} mode)
        _b11_fa4_expect("${_bundle}" "${_prefix}" entries ${_index} symbol_prefix)
        _b11_fa4_expect("${_bundle}" "${_relative}" entries ${_index} directory)
        string(JSON _manifest_hash GET "${_bundle}" entries ${_index} manifest_sha256)
        _b11_fa4_hash("${_dir}/${_prefix}.json" "${_manifest_hash}")
        _b11_fa4_validate_one("${_dir}" "${_prefix}" "${_mode}" "${_batch}")
        list(APPEND _sources "${_dir}/${_prefix}_bridge.cpp" "${_dir}/${_prefix}.o")
        list(APPEND _includes "${_dir}")
        math(EXPR _index "${_index} + 1")
      endforeach()
    endforeach()
    set(${out_static} TRUE PARENT_SCOPE)
  else()
    # Schema 1 remains supported as an explicit dynamic-B exact/mask pair.
    foreach(_mode IN ITEMS exact mask)
      set(_prefix "b11_fa4_${_mode}_m128_n96_s1")
      set(_dir "${root}/${_mode}")
      _b11_fa4_validate_one("${_dir}" "${_prefix}" "${_mode}" 0)
      list(APPEND _sources "${_dir}/${_prefix}_bridge.cpp" "${_dir}/${_prefix}.o")
      list(APPEND _includes "${_dir}")
    endforeach()
    set(${out_static} FALSE PARENT_SCOPE)
  endif()
  set(${out_sources} "${_sources}" PARENT_SCOPE)
  set(${out_includes} "${_includes}" PARENT_SCOPE)
endfunction()
